drop table if exists kyujin_uketsukes;
create table  kyujin_uketsukes(
      id                INT not null auto_increment,
      uketsuke_nen      INT,
      uketsuke_date	varchar(16),
      uketsuke_code     varchar(8),
      uketsuke_bango	INT,
      kigyo_bango	INT,
      shokushu_bango	INT,
      shokushu_mei	varchar(128),
      shokugyo_code	INT,
      tenkin	        INT,
      koutai	        INT,
      kihonkyu	        INT,
      kijunnai_tingin	INT,
      kikai	        varchar(4),
      denki	        varchar(4),
      joho	        varchar(4),
      kouka	        varchar(4),
      kenchiku	        varchar(4),
      kei	        INT,
      kyujin_sosu       INT,
      sintai	        INT,
      kengaku	        INT,
      heigan            INT,
      bikou	        varchar(128),
      irai_jikou        varchar(256),
      input_date        datetime,
      primary key (id)
);
