# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "groups", :force => true do |t|
    t.column "group_name", :string, :limit => 40, :null => false
  end

  create_table "kigyo_daichos", :force => true do |t|
    t.column "kigyo_bango",    :integer,                 :null => false
    t.column "jigyosho_mei1",  :string,   :limit => 128
    t.column "jigyosho_mei2",  :string,   :limit => 64
    t.column "furikana",       :string,   :limit => 128
    t.column "shozaichi",      :string,   :limit => 32
    t.column "yubin_zip",      :integer
    t.column "shozaichi1",     :string,   :limit => 128
    t.column "shozaichi2",     :string,   :limit => 64
    t.column "tantou_yaku",    :string,   :limit => 64
    t.column "tantou_mei",     :string,   :limit => 32
    t.column "tele_number",    :string,   :limit => 32
    t.column "sangyo_code",    :integer
    t.column "seisan_hinmoku", :string,   :limit => 256
    t.column "input_date",     :datetime
  end

  create_table "kigyo_homons", :force => true do |t|
    t.column "kigyo_bango",   :integer,                 :null => false
    t.column "senmon_kamei",  :string,  :limit => 8
    t.column "jigyosho_mei1", :string,  :limit => 128
    t.column "jigyosho_mei2", :string,  :limit => 128
    t.column "kyujin_jokyo",  :string,  :limit => 1024
    t.column "ob_yosu",       :string,  :limit => 1024
    t.column "visit_date",    :date
  end

  create_table "kigyo_infos", :force => true do |t|
    t.column "kigyo_number",    :integer
    t.column "sangyo_code",     :integer
    t.column "jugyoinsu",       :integer
    t.column "sihon_oku",       :integer
    t.column "sihon_senman",    :integer
    t.column "input_date",      :datetime
    t.column "kigyo_daicho_id", :integer
  end

  create_table "kyujin_uketsukes", :force => true do |t|
    t.column "uketsuke_nen",    :integer
    t.column "uketsuke_date",   :string,   :limit => 16
    t.column "uketsuke_code",   :string,   :limit => 8
    t.column "uketsuke_bango",  :integer
    t.column "kigyo_bango",     :integer
    t.column "shokushu_bango",  :integer
    t.column "shokushu_mei",    :string,   :limit => 128
    t.column "shokugyo_code",   :integer
    t.column "tenkin",          :integer
    t.column "koutai",          :integer
    t.column "kihonkyu",        :integer
    t.column "kijunnai_tingin", :integer
    t.column "kikai",           :string,   :limit => 4
    t.column "denki",           :string,   :limit => 4
    t.column "joho",            :string,   :limit => 4
    t.column "kouka",           :string,   :limit => 4
    t.column "kenchiku",        :string,   :limit => 4
    t.column "kei",             :integer
    t.column "kyujin_sosu",     :integer
    t.column "sintai",          :integer
    t.column "kengaku",         :integer
    t.column "heigan",          :integer
    t.column "bikou",           :string,   :limit => 128
    t.column "irai_jikou",      :string,   :limit => 256
    t.column "input_date",      :datetime
  end

  create_table "student_nenjis", :force => true do |t|
    t.column "nendo",      :integer, :null => false
    t.column "gakunen",    :integer, :null => false
    t.column "kumi",       :integer, :null => false
    t.column "bango",      :integer, :null => false
    t.column "student_id", :integer, :null => false
  end

  add_index "student_nenjis", ["student_id"], :name => "student_id"

  create_table "students", :force => true do |t|
    t.column "nyugakuid", :string,  :limit => 40, :null => false
    t.column "name_sei",  :string,  :limit => 40
    t.column "name_mei",  :string,  :limit => 40
    t.column "sex",       :integer,               :null => false
    t.column "group_id",  :integer,               :null => false
    t.column "ka",        :integer
  end

  create_table "teacher_nenjis", :force => true do |t|
    t.column "nendo",       :integer,               :null => false
    t.column "bunsho",      :string,  :limit => 40, :null => false
    t.column "gakunen",     :integer,               :null => false
    t.column "tannin_ka",   :integer
    t.column "tennin_kumi", :integer
    t.column "teacher_id",  :integer,               :null => false
  end

  create_table "teachers", :force => true do |t|
    t.column "name_sei",      :string,  :limit => 40, :null => false
    t.column "name_mei",      :string,  :limit => 40, :null => false
    t.column "sex",           :integer
    t.column "kyoka",         :string,  :limit => 40, :null => false
    t.column "tennyu_nen",    :integer
    t.column "tenshutsu_nen", :integer
    t.column "user_id",       :integer,               :null => false
  end

  create_table "uketsuke_pdfs", :force => true do |t|
    t.column "uketsuke_bango",     :integer
    t.column "pdf_name",           :string,   :limit => 32
    t.column "uketsuke_nen",       :integer
    t.column "input_date",         :datetime
    t.column "shokushu_bango",     :integer
    t.column "kyujin_uketsuke_id", :integer
  end

  create_table "uketsuke_rireki_motos", :force => true do |t|
    t.column "kigyo_bango", :integer, :null => false
    t.column "uke1999",     :integer
    t.column "uke2000",     :integer
    t.column "uke2001",     :integer
    t.column "uke2002",     :integer
    t.column "uke2003",     :integer
    t.column "uke2004",     :integer
    t.column "uke2005",     :integer
    t.column "uke2006",     :integer
    t.column "uke2007",     :integer
  end

  create_table "uketsuke_rirekis", :force => true do |t|
    t.column "kigyo_bango",     :integer
    t.column "uketsuke_nen",    :integer
    t.column "uketsuke_bango",  :integer
    t.column "kigyo_daicho_id", :integer
    t.column "kyujinhyo_maisu", :integer
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string,   :limit => 40,  :null => false
    t.column "name",                      :string,   :limit => 80
    t.column "email",                     :string,   :limit => 100
    t.column "crypted_password",          :string,   :limit => 40,  :null => false
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string,   :limit => 80
    t.column "remember_token_expires_at", :datetime
    t.column "group_id",                  :integer,                 :null => false
  end

  create_table "zips", :force => true do |t|
    t.column "zip",           :string,  :limit => 7
    t.column "prefecture_id", :integer
    t.column "city",          :string,  :limit => 64
    t.column "town",          :string,  :limit => 254
  end

end
